# Generated by Django 3.2.25 on 2025-05-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnuDatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('snmpindex', models.CharField(max_length=100)),
                ('snmpindexonu', models.CharField(max_length=50, unique=True)),
                ('slotportonu', models.CharField(max_length=30)),
                ('onudesc', models.CharField(max_length=255)),
                ('serialonu', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('onulogico', models.IntegerField()),
                ('act_susp', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'onu_datos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloqueEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Bloque')),
                ('activo', models.BooleanField(default=False, verbose_name='Bloque Activo')),
                ('frecuencia', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2, verbose_name='Frecuencia (minuto de la hora)')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Control de Ejecución',
                'verbose_name_plural': 'Controles de Ejecución',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin Título', max_length=100, verbose_name='Título del Script')),
                ('archivo', models.CharField(default='default.sh', max_length=200, verbose_name='Script')),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('modo', 'Modo')], max_length=20, verbose_name='Tipo de Script')),
                ('ejecucion_automatica', models.BooleanField(default=True, verbose_name='Ejecutar automáticamente')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('log', models.TextField(blank=True, null=True)),
                ('salida', models.TextField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.script')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueEjecucionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Final')),
                ('estado', models.CharField(default='pendiente', max_length=20, verbose_name='Estado')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Log')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.bloqueejecucion', verbose_name='Bloque')),
            ],
        ),
        migrations.AddField(
            model_name='bloqueejecucion',
            name='scripts',
            field=models.ManyToManyField(to='scripts.Script', verbose_name='Scripts incluidos'),
        ),
    ]
