# Generated by Django 3.2.25 on 2025-03-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='script',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='script',
            name='orden',
        ),
        migrations.AddField(
            model_name='script',
            name='archivo',
            field=models.CharField(default='default.sh', max_length=200, verbose_name='Script'),
        ),
        migrations.AddField(
            model_name='script',
            name='titulo',
            field=models.CharField(default='Sin Título', max_length=100, verbose_name='Título del Script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('modo', 'Modo')], max_length=20, verbose_name='Tipo de Script'),
        ),
        migrations.DeleteModel(
            name='ExecutionRecord',
        ),
    ]
