# Generated by Django 3.2.25 on 2025-03-04 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20250303_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('log', models.TextField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.script')),
            ],
        ),
    ]
