# Generated by Django 3.2.25 on 2025-03-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_executioncontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Bloque')),
                ('activo', models.BooleanField(default=False, verbose_name='Bloque Activo')),
                ('scripts', models.ManyToManyField(to='scripts.Script', verbose_name='Scripts incluidos')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueEjecucionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Final')),
                ('estado', models.CharField(default='pendiente', max_length=20, verbose_name='Estado')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Log')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.bloqueejecucion', verbose_name='Bloque')),
            ],
        ),
    ]
