# Generated by Django 3.2.25 on 2025-03-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_bloqueejecucion_bloqueejecucionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueejecucion',
            name='frecuencia',
            field=models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2, verbose_name='Frecuencia (minuto de la hora)'),
        ),
    ]
