# Generated by Django 3.2.25 on 2025-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_bloqueejecucion_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='ejecucion_automatica',
            field=models.BooleanField(default=True, verbose_name='Ejecutar automáticamente'),
        ),
    ]
