# Generated by Django 3.2.25 on 2025-03-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_script_ejecucion_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnuDatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('snmpindex', models.CharField(max_length=100)),
                ('snmpindexonu', models.CharField(max_length=50, unique=True)),
                ('slotportonu', models.CharField(max_length=30)),
                ('onudesc', models.CharField(max_length=255)),
                ('serialonu', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('onulogico', models.IntegerField()),
                ('act_susp', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'onu_datos',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='salida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
