# Generated by Django 3.2.25 on 2025-06-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionTareaSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Ejecución'), ('C', 'Completada'), ('F', 'Fallida')], default='P', max_length=1)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ejecución de Tarea',
                'verbose_name_plural': 'Ejecuciones de Tareas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Host')),
                ('ip', models.GenericIPAddressField(verbose_name='IP del OLT')),
                ('comunidad', models.CharField(default='publica', max_length=50, verbose_name='Comunidad SNMP')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Trabajo')),
                ('tipo', models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('onudesc', 'Descripción ONU'), ('estado_onu', 'Estado ONU'), ('plan_onu', 'Plan ONU'), ('pot_rx', 'Potencia RX'), ('pot_tx', 'Potencia TX'), ('last_down_t', 'Last Down Time'), ('distancia_m', 'Distancia (m)'), ('modelo_onu', 'Modelo ONU')], max_length=20, verbose_name='Tipo de Tarea')),
                ('modo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('modo', 'Modo Especial')], default='principal', max_length=20, verbose_name='Modo de Ejecución')),
                ('intervalo', models.CharField(choices=[('00', '(00)'), ('15', '(15)'), ('30', '(30)'), ('45', '(45)')], default='00', max_length=2, verbose_name='Intervalo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Trabajo SNMP',
                'verbose_name_plural': 'Trabajos SNMP',
                'ordering': ['nombre'],
                'unique_together': {('tipo', 'modo', 'intervalo')},
            },
        ),
        migrations.CreateModel(
            name='TareaSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Tarea')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Modificación')),
                ('registros_activos', models.PositiveIntegerField(default=0, help_text='Contador actualizado automáticamente', verbose_name='ONUs Registradas')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('hosts', models.ManyToManyField(to='snmp_scheduler.Host', verbose_name='Hosts')),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snmp_scheduler.trabajosnmp', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Tarea SNMP',
                'verbose_name_plural': 'Tareas SNMP',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ejecuciontareasnmp',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snmp_scheduler.host', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='ejecuciontareasnmp',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='snmp_scheduler.tareasnmp'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('snmp_scheduler.tareasnmp',),
        ),
    ]
