# Generated by Django 3.2.25 on 2025-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='desactivado_por_timeout',
            field=models.BooleanField(default=False, help_text='Indica si el host fue desactivado por el protocolo anti-timeout'),
        ),
        migrations.AddField(
            model_name='host',
            name='ultimo_timeout',
            field=models.DateTimeField(blank=True, help_text='Última vez que el host tuvo un timeout', null=True),
        ),
    ]
