# Generated by Django 3.2.25 on 2025-06-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasnmp',
            name='tipo',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('onudesc', 'Descripción ONU'), ('estado_onu', 'Estado ONU'), ('plan_onu', 'Plan ONU'), ('pot_rx', 'Potencia RX'), ('pot_tx', 'Potencia TX'), ('last_down_t', 'Last Down Time'), ('distancia_m', 'Distancia (m)'), ('modelo_onu', 'Modelo ONU')], default='descubrimiento', max_length=20),
        ),
    ]
