# Generated by Django 3.2.25 on 2025-05-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionTareaSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Ejecución'), ('C', 'Completada'), ('F', 'Fallida')], default='P', max_length=1)),
                ('resultado', models.JSONField(null=True)),
                ('error', models.TextField(null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='snmp_scheduler.tareasnmp')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
