# Generated by Django 3.2.25 on 2025-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0002_auto_20250615_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnuDato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('snmpindex', models.CharField(max_length=100)),
                ('snmpindexonu', models.CharField(max_length=50)),
                ('slotportonu', models.CharField(max_length=30)),
                ('onulogico', models.IntegerField()),
                ('host_name', models.CharField(blank=True, max_length=50, null=True)),
                ('onudesc', models.CharField(blank=True, max_length=255, null=True)),
                ('act_susp', models.CharField(max_length=10)),
                ('serialonu', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('enviar', models.BooleanField(default=False)),
                ('estado_onu', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_onu', models.CharField(blank=True, max_length=50, null=True)),
                ('potencia_rx', models.CharField(blank=True, max_length=50, null=True)),
                ('potencia_tx', models.CharField(blank=True, max_length=50, null=True)),
                ('last_down_time', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia_m', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_onu', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'onu_datos',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['host', 'snmpindexonu'], name='idx_host_snmpindexonu'),
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['fecha'], name='idx_fecha'),
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['estado_onu'], name='idx_estado_onu'),
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['modelo_onu'], name='idx_modelo_onu'),
        ),
        migrations.AddConstraint(
            model_name='onudato',
            constraint=models.UniqueConstraint(fields=('host', 'snmpindexonu'), name='unique_host_snmpindexonu'),
        ),
    ]
