# Generated by Django 3.2.25 on 2025-06-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0002_ejecuciontareasnmp_host_onudato_supervisor_tareasnmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasnmp',
            name='comunidad',
        ),
        migrations.AddField(
            model_name='host',
            name='comunidad',
            field=models.CharField(default='publica', max_length=50, verbose_name='Comunidad SNMP'),
        ),
    ]
