# Generated by Django 3.2.25 on 2025-05-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0002_ejecuciontareasnmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasnmp',
            name='intervalo',
            field=models.CharField(choices=[('00', '(00)'), ('15', '(15)'), ('30', '(30)'), ('45', '(45)')], default='00', max_length=10),
        ),
    ]
