# Generated by Django 3.2.25 on 2025-05-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0003_alter_tareasnmp_intervalo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecuciontareasnmp',
            options={'ordering': ['-inicio'], 'verbose_name': 'Ejecución de Tarea', 'verbose_name_plural': 'Ejecuciones de Tareas'},
        ),
        migrations.AlterField(
            model_name='tareasnmp',
            name='tipo',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('datos', 'Datos')], default='descubrimiento', max_length=20),
        ),
    ]
