# Generated by Django 3.2.25 on 2025-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0003_auto_20250611_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasnmp',
            name='intervalo',
            field=models.CharField(choices=[('00', '(00)'), ('15', '(15)'), ('30', '(30)'), ('45', '(45)')], default='00', max_length=2, verbose_name='Intervalo'),
        ),
    ]
