# Generated by Django 3.2.25 on 2025-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0004_auto_20250516_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasnmp',
            name='tipo',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('datos', 'Datos'), ('datos_bulk', 'Recolección Masiva de Datos')], default='descubrimiento', max_length=20),
        ),
    ]
