# Generated by Django 3.2.25 on 2025-06-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0004_alter_tareasnmp_intervalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasnmp',
            name='oid_consulta',
        ),
        migrations.AddField(
            model_name='tareasnmp',
            name='modo',
            field=models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('modo', 'Modo Especial')], default='principal', max_length=20, verbose_name='Modo de Ejecución'),
        ),
    ]
