# Generated by Django 3.2.25 on 2025-06-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0005_auto_20250611_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasnmp',
            name='intervalo',
        ),
        migrations.RemoveField(
            model_name='tareasnmp',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='tareasnmp',
            name='tipo',
        ),
        migrations.CreateModel(
            name='TrabajoSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Trabajo')),
                ('tipo', models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('onudesc', 'Descripción ONU'), ('estado_onu', 'Estado ONU'), ('plan_onu', 'Plan ONU'), ('pot_rx', 'Potencia RX'), ('pot_tx', 'Potencia TX'), ('last_down_t', 'Last Down Time'), ('distancia_m', 'Distancia (m)'), ('modelo_onu', 'Modelo ONU')], max_length=20, verbose_name='Tipo de Tarea')),
                ('modo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('modo', 'Modo Especial')], default='principal', max_length=20, verbose_name='Modo de Ejecución')),
                ('intervalo', models.CharField(choices=[('00', '(00)'), ('15', '(15)'), ('30', '(30)'), ('45', '(45)')], default='00', max_length=2, verbose_name='Intervalo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Trabajo SNMP',
                'verbose_name_plural': 'Trabajos SNMP',
                'ordering': ['nombre'],
                'unique_together': {('tipo', 'modo', 'intervalo')},
            },
        ),
        migrations.AddField(
            model_name='tareasnmp',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snmp_scheduler.trabajosnmp', verbose_name='Trabajo'),
        ),
    ]
