# Generated by Django 3.2.25 on 2025-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0005_alter_tareasnmp_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasnmp',
            name='oid_consulta',
        ),
        migrations.AddField(
            model_name='tareasnmp',
            name='bulk_subtipo',
            field=models.CharField(blank=True, choices=[('onudesc', 'Descripción ONU'), ('estado_onu', 'Estado ONU'), ('last_down', 'Última desconexión'), ('pot_rx', 'Potencia RX'), ('pot_tx', 'Potencia TX'), ('last_down_t', 'Last Down Time'), ('distancia_m', 'Distancia (m)'), ('modelo_onu', 'Modelo ONU')], help_text='Cuando sea Recolección Masiva de Datos, elige el dato a extraer', max_length=20, null=True, verbose_name='Subtipo Bulk'),
        ),
        migrations.AlterField(
            model_name='ejecuciontareasnmp',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecuciontareasnmp',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecuciontareasnmp',
            name='resultado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
