# Generated by Django 3.2.25 on 2025-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0006_auto_20250524_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareasnmp',
            name='oid_consulta',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='OID Automático'),
        ),
        migrations.AlterField(
            model_name='tareasnmp',
            name='bulk_subtipo',
            field=models.CharField(blank=True, choices=[('onudesc', 'Descripción ONU'), ('estado_onu', 'Estado ONU'), ('last_down', 'Última desconexión'), ('pot_rx', 'Potencia RX'), ('pot_tx', 'Potencia TX'), ('last_down_t', 'Last Down Time'), ('distancia_m', 'Distancia (m)'), ('modelo_onu', 'Modelo ONU')], help_text='Cuando sea Recolección Masiva de Datos, elige qué dato extraer', max_length=20, null=True, verbose_name='Subtipo Bulk'),
        ),
    ]
