# Generated by Django 3.2.25 on 2025-06-12 01:37

from django.db import migrations, models
import django.db.models.deletion

def migrate_hosts(apps, schema_editor):
    TareaSNMP = apps.get_model('snmp_scheduler', 'TareaSNMP')
    EjecucionTareaSNMP = apps.get_model('snmp_scheduler', 'EjecucionTareaSNMP')
    
    # Migrar hosts de tareas
    for tarea in TareaSNMP.objects.all():
        if hasattr(tarea, 'host_id') and tarea.host_id:
            tarea.hosts.add(tarea.host_id)
            
            # Actualizar las ejecuciones existentes
            EjecucionTareaSNMP.objects.filter(tarea=tarea).update(host_id=tarea.host_id)

def reverse_migrate_hosts(apps, schema_editor):
    TareaSNMP = apps.get_model('snmp_scheduler', 'TareaSNMP')
    for tarea in TareaSNMP.objects.all():
        if tarea.hosts.exists():
            tarea.host_id = tarea.hosts.first().id
            tarea.save()

class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0006_auto_20250611_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecuciontareasnmp',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snmp_scheduler.host', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='tareasnmp',
            name='hosts',
            field=models.ManyToManyField(to='snmp_scheduler.host', verbose_name='Hosts'),
        ),
        migrations.RunPython(migrate_hosts, reverse_migrate_hosts),
        migrations.RemoveField(
            model_name='tareasnmp',
            name='host',
        ),
    ]
