# Generated by Django 3.2.25 on 2025-06-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0007_auto_20250611_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onudato',
            options={'managed': True, 'verbose_name': 'Datos ONU', 'verbose_name_plural': 'Datos ONUs'},
        ),
    ]
