# Generated by Django 3.2.25 on 2025-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0007_auto_20250524_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareasnmp',
            options={'verbose_name': 'Tarea SNMP'},
        ),
        migrations.RemoveField(
            model_name='tareasnmp',
            name='bulk_subtipo',
        ),
        migrations.AlterField(
            model_name='tareasnmp',
            name='tipo',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('onudesc', 'Descripción ONU'), ('estado_onu', 'Estado ONU'), ('last_down', 'Última desconexión'), ('pot_rx', 'Potencia RX'), ('pot_tx', 'Potencia TX'), ('last_down_t', 'Last Down Time'), ('distancia_m', 'Distancia (m)'), ('modelo_onu', 'Modelo ONU'), ('datos', 'Datos (ONU Desc)')], default='descubrimiento', max_length=20),
        ),
    ]
