# Generated by Django 3.2.25 on 2025-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0008_alter_onudato_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onudato',
            options={'managed': True},
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['host', 'snmpindexonu'], name='onu_datos_host_68933e_idx'),
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['fecha'], name='onu_datos_fecha_17e779_idx'),
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['estado_onu'], name='onu_datos_estado__17d60c_idx'),
        ),
        migrations.AddIndex(
            model_name='onudato',
            index=models.Index(fields=['modelo_onu'], name='onu_datos_modelo__e2c5db_idx'),
        ),
        migrations.AddConstraint(
            model_name='onudato',
            constraint=models.UniqueConstraint(fields=('host', 'snmpindexonu'), name='unique_host_snmpindexonu'),
        ),
    ]
