# Generated by Django 3.2.25 on 2025-06-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0009_auto_20250614_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onudato',
            options={'managed': False},
        ),
    ]
