# Generated by Django 3.2.25 on 2025-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0009_alter_tareasnmp_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('snmp_scheduler.tareasnmp',),
        ),
        migrations.AlterUniqueTogether(
            name='tareasnmp',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tareasnmp',
            constraint=models.UniqueConstraint(condition=models.Q(('modo__in', ['principal', 'modo'])), fields=('host_ip', 'intervalo', 'modo'), name='unique_principal_modo'),
        ),
        migrations.AddConstraint(
            model_name='tareasnmp',
            constraint=models.UniqueConstraint(condition=models.Q(('modo', 'secundario')), fields=('host_ip', 'intervalo', 'modo', 'tipo'), name='unique_secundario_por_tipo'),
        ),
    ]
