# Generated by Django 3.2.25 on 2025-06-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_scheduler', '0010_alter_onudato_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onudato',
            options={'managed': True},
        ),
    ]
